#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 15

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_sig = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_abstract = 5,
  sym_var = 6,
  anon_sym_COMMA = 7,
  anon_sym_extends = 8,
  anon_sym_in = 9,
  anon_sym_PLUS = 10,
  anon_sym_disj = 11,
  anon_sym_COLON = 12,
  anon_sym_DASH = 13,
  aux_sym_constant_token1 = 14,
  aux_sym_constant_token2 = 15,
  anon_sym_none = 16,
  anon_sym_univ = 17,
  anon_sym_iden = 18,
  anon_sym_one = 19,
  anon_sym_lone = 20,
  anon_sym_some = 21,
  sym_source_file = 22,
  sym__definition = 23,
  sym_sig_definition = 24,
  sym_name_list = 25,
  sym__name_list = 26,
  sym_sig_extends = 27,
  sym_sig_in = 28,
  sym_sig_in_list = 29,
  sym_field_list = 30,
  sym__field_list = 31,
  sym_field_declaration = 32,
  sym_expression = 33,
  sym_constant = 34,
  sym_multiplicity = 35,
  sym_qualified_name = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_sig_in_list_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_sig] = "sig",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_abstract] = "abstract",
  [sym_var] = "var",
  [anon_sym_COMMA] = ",",
  [anon_sym_extends] = "extends",
  [anon_sym_in] = "in",
  [anon_sym_PLUS] = "+",
  [anon_sym_disj] = "disj",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH] = "-",
  [aux_sym_constant_token1] = "constant_token1",
  [aux_sym_constant_token2] = "constant_token2",
  [anon_sym_none] = "none",
  [anon_sym_univ] = "univ",
  [anon_sym_iden] = "iden",
  [anon_sym_one] = "one",
  [anon_sym_lone] = "lone",
  [anon_sym_some] = "some",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_sig_definition] = "sig_definition",
  [sym_name_list] = "name_list",
  [sym__name_list] = "_name_list",
  [sym_sig_extends] = "sig_extends",
  [sym_sig_in] = "sig_in",
  [sym_sig_in_list] = "sig_in_list",
  [sym_field_list] = "field_list",
  [sym__field_list] = "_field_list",
  [sym_field_declaration] = "field_declaration",
  [sym_expression] = "expression",
  [sym_constant] = "constant",
  [sym_multiplicity] = "multiplicity",
  [sym_qualified_name] = "qualified_name",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_sig_in_list_repeat1] = "sig_in_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_sig] = anon_sym_sig,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_abstract] = sym_abstract,
  [sym_var] = sym_var,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_disj] = anon_sym_disj,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_constant_token1] = aux_sym_constant_token1,
  [aux_sym_constant_token2] = aux_sym_constant_token2,
  [anon_sym_none] = anon_sym_none,
  [anon_sym_univ] = anon_sym_univ,
  [anon_sym_iden] = anon_sym_iden,
  [anon_sym_one] = anon_sym_one,
  [anon_sym_lone] = anon_sym_lone,
  [anon_sym_some] = anon_sym_some,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_sig_definition] = sym_sig_definition,
  [sym_name_list] = sym_name_list,
  [sym__name_list] = sym__name_list,
  [sym_sig_extends] = sym_sig_extends,
  [sym_sig_in] = sym_sig_in,
  [sym_sig_in_list] = sym_sig_in_list,
  [sym_field_list] = sym_field_list,
  [sym__field_list] = sym__field_list,
  [sym_field_declaration] = sym_field_declaration,
  [sym_expression] = sym_expression,
  [sym_constant] = sym_constant,
  [sym_multiplicity] = sym_multiplicity,
  [sym_qualified_name] = sym_qualified_name,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_sig_in_list_repeat1] = aux_sym_sig_in_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_sig] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_abstract] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_disj] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_constant_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constant_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_univ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_iden] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_one] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lone] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_some] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_sig_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym__name_list] = {
    .visible = false,
    .named = true,
  },
  [sym_sig_extends] = {
    .visible = true,
    .named = true,
  },
  [sym_sig_in] = {
    .visible = true,
    .named = true,
  },
  [sym_sig_in_list] = {
    .visible = true,
    .named = true,
  },
  [sym_field_list] = {
    .visible = true,
    .named = true,
  },
  [sym__field_list] = {
    .visible = false,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicity] = {
    .visible = true,
    .named = true,
  },
  [sym_qualified_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sig_in_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_extends = 1,
  field_fields = 2,
  field_in_list = 3,
  field_names = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_extends] = "extends",
  [field_fields] = "fields",
  [field_in_list] = "in_list",
  [field_names] = "names",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 2},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 2},
  [11] = {.index = 15, .length = 1},
  [12] = {.index = 16, .length = 2},
  [13] = {.index = 18, .length = 2},
  [14] = {.index = 20, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_names, 1},
  [1] =
    {field_extends, 1},
  [2] =
    {field_in_list, 1},
  [3] =
    {field_fields, 3},
    {field_names, 1},
  [5] =
    {field_names, 2},
  [6] =
    {field_fields, 4},
    {field_names, 1},
  [8] =
    {field_fields, 4},
    {field_names, 2},
  [10] =
    {field_names, 3},
  [11] =
    {field_fields, 5},
    {field_names, 2},
  [13] =
    {field_fields, 5},
    {field_names, 3},
  [15] =
    {field_names, 4},
  [16] =
    {field_fields, 6},
    {field_names, 3},
  [18] =
    {field_fields, 6},
    {field_names, 4},
  [20] =
    {field_fields, 7},
    {field_names, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 5,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 67,
  [73] = 63,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '+') ADVANCE(5);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_constant_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_constant_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == 'v') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'b') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'd') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'j') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_one);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_sig);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 32:
      if (lookahead == 'v') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_var);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_disj);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_iden);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_lone);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_some);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_univ);
      END_STATE();
    case 42:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 43:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_abstract);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_sig] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_abstract] = ACTIONS(1),
    [sym_var] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_disj] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [aux_sym_constant_token1] = ACTIONS(1),
    [aux_sym_constant_token2] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [anon_sym_univ] = ACTIONS(1),
    [anon_sym_iden] = ACTIONS(1),
    [anon_sym_one] = ACTIONS(1),
    [anon_sym_lone] = ACTIONS(1),
    [anon_sym_some] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [sym__definition] = STATE(2),
    [sym_sig_definition] = STATE(2),
    [sym_multiplicity] = STATE(91),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_sig] = ACTIONS(5),
    [sym_abstract] = ACTIONS(7),
    [sym_var] = ACTIONS(9),
    [anon_sym_one] = ACTIONS(11),
    [anon_sym_lone] = ACTIONS(11),
    [anon_sym_some] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      anon_sym_sig,
    ACTIONS(7), 1,
      sym_abstract,
    ACTIONS(9), 1,
      sym_var,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(91), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
    STATE(3), 3,
      sym__definition,
      sym_sig_definition,
      aux_sym_source_file_repeat1,
  [26] = 7,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_sig,
    ACTIONS(20), 1,
      sym_abstract,
    ACTIONS(23), 1,
      sym_var,
    STATE(91), 1,
      sym_multiplicity,
    ACTIONS(26), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
    STATE(3), 3,
      sym__definition,
      sym_sig_definition,
      aux_sym_source_file_repeat1,
  [52] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(79), 1,
      sym_field_list,
    STATE(82), 1,
      sym__field_list,
  [80] = 8,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    STATE(45), 1,
      sym__name_list,
    STATE(72), 1,
      sym_field_declaration,
    STATE(73), 1,
      sym__field_list,
    STATE(75), 1,
      sym_name_list,
    ACTIONS(37), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [106] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(80), 1,
      sym_field_list,
    STATE(82), 1,
      sym__field_list,
  [134] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(82), 1,
      sym__field_list,
    STATE(95), 1,
      sym_field_list,
  [162] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(82), 1,
      sym__field_list,
    STATE(96), 1,
      sym_field_list,
  [190] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(74), 1,
      sym_field_list,
    STATE(75), 1,
      sym_name_list,
    STATE(82), 1,
      sym__field_list,
  [218] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(82), 1,
      sym__field_list,
    STATE(83), 1,
      sym_field_list,
  [246] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(82), 1,
      sym__field_list,
    STATE(85), 1,
      sym_field_list,
  [274] = 9,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(51), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(67), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
    STATE(82), 1,
      sym__field_list,
    STATE(92), 1,
      sym_field_list,
  [302] = 5,
    ACTIONS(53), 1,
      anon_sym_disj,
    ACTIONS(55), 1,
      anon_sym_DASH,
    STATE(58), 1,
      sym_expression,
    STATE(62), 1,
      sym_constant,
    ACTIONS(57), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [321] = 8,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(33), 1,
      sym_var,
    ACTIONS(35), 1,
      anon_sym_disj,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      sym__name_list,
    STATE(63), 1,
      sym__field_list,
    STATE(72), 1,
      sym_field_declaration,
    STATE(75), 1,
      sym_name_list,
  [346] = 5,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(59), 1,
      anon_sym_disj,
    STATE(60), 1,
      sym_expression,
    STATE(62), 1,
      sym_constant,
    ACTIONS(57), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [365] = 5,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(61), 1,
      anon_sym_disj,
    STATE(62), 1,
      sym_constant,
    STATE(65), 1,
      sym_expression,
    ACTIONS(57), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [384] = 1,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [394] = 1,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [404] = 1,
    ACTIONS(67), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [414] = 1,
    ACTIONS(69), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [424] = 1,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [434] = 4,
    ACTIONS(55), 1,
      anon_sym_DASH,
    STATE(62), 1,
      sym_constant,
    STATE(65), 1,
      sym_expression,
    ACTIONS(57), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [450] = 1,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [460] = 1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [470] = 1,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [480] = 1,
    ACTIONS(79), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [490] = 4,
    ACTIONS(55), 1,
      anon_sym_DASH,
    STATE(62), 1,
      sym_constant,
    STATE(68), 1,
      sym_expression,
    ACTIONS(57), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [506] = 1,
    ACTIONS(81), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [516] = 1,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [526] = 1,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [536] = 1,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [546] = 4,
    ACTIONS(55), 1,
      anon_sym_DASH,
    STATE(60), 1,
      sym_expression,
    STATE(62), 1,
      sym_constant,
    ACTIONS(57), 4,
      aux_sym_constant_token2,
      anon_sym_none,
      anon_sym_univ,
      anon_sym_iden,
  [562] = 1,
    ACTIONS(89), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [572] = 1,
    ACTIONS(91), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [582] = 1,
    ACTIONS(93), 7,
      ts_builtin_sym_end,
      anon_sym_sig,
      sym_abstract,
      sym_var,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [592] = 4,
    ACTIONS(95), 1,
      anon_sym_sig,
    ACTIONS(97), 1,
      sym_abstract,
    STATE(87), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [607] = 2,
    ACTIONS(101), 1,
      anon_sym_COMMA,
    ACTIONS(99), 4,
      anon_sym_LBRACE,
      anon_sym_extends,
      anon_sym_in,
      anon_sym_COLON,
  [617] = 4,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 1,
      anon_sym_extends,
    ACTIONS(107), 1,
      anon_sym_in,
    STATE(81), 2,
      sym_sig_extends,
      sym_sig_in,
  [631] = 4,
    ACTIONS(105), 1,
      anon_sym_extends,
    ACTIONS(107), 1,
      anon_sym_in,
    ACTIONS(109), 1,
      anon_sym_LBRACE,
    STATE(77), 2,
      sym_sig_extends,
      sym_sig_in,
  [645] = 4,
    ACTIONS(105), 1,
      anon_sym_extends,
    ACTIONS(107), 1,
      anon_sym_in,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(90), 2,
      sym_sig_extends,
      sym_sig_in,
  [659] = 3,
    ACTIONS(113), 1,
      anon_sym_sig,
    STATE(76), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [671] = 3,
    ACTIONS(95), 1,
      anon_sym_sig,
    STATE(87), 1,
      sym_multiplicity,
    ACTIONS(11), 3,
      anon_sym_one,
      anon_sym_lone,
      anon_sym_some,
  [683] = 4,
    ACTIONS(105), 1,
      anon_sym_extends,
    ACTIONS(107), 1,
      anon_sym_in,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    STATE(93), 2,
      sym_sig_extends,
      sym_sig_in,
  [697] = 1,
    ACTIONS(117), 4,
      anon_sym_LBRACE,
      anon_sym_extends,
      anon_sym_in,
      anon_sym_COLON,
  [704] = 1,
    ACTIONS(119), 4,
      anon_sym_LBRACE,
      anon_sym_extends,
      anon_sym_in,
      anon_sym_COLON,
  [711] = 4,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_disj,
    STATE(45), 1,
      sym__name_list,
    STATE(78), 1,
      sym_name_list,
  [724] = 3,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(55), 1,
      sym_qualified_name,
    STATE(88), 1,
      sym_sig_in_list,
  [734] = 3,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(45), 1,
      sym__name_list,
    STATE(89), 1,
      sym_name_list,
  [744] = 3,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(129), 1,
      anon_sym_PLUS,
    STATE(56), 1,
      aux_sym_sig_in_list_repeat1,
  [754] = 3,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(45), 1,
      sym__name_list,
    STATE(78), 1,
      sym_name_list,
  [764] = 3,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(38), 1,
      sym_name_list,
    STATE(45), 1,
      sym__name_list,
  [774] = 3,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(40), 1,
      sym_name_list,
    STATE(45), 1,
      sym__name_list,
  [784] = 3,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(39), 1,
      sym_name_list,
    STATE(45), 1,
      sym__name_list,
  [794] = 3,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(43), 1,
      sym_name_list,
    STATE(45), 1,
      sym__name_list,
  [804] = 3,
    ACTIONS(129), 1,
      anon_sym_PLUS,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      aux_sym_sig_in_list_repeat1,
  [814] = 3,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
    ACTIONS(135), 1,
      anon_sym_PLUS,
    STATE(56), 1,
      aux_sym_sig_in_list_repeat1,
  [824] = 2,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(44), 1,
      sym__name_list,
  [831] = 1,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [836] = 2,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(64), 1,
      sym_qualified_name,
  [843] = 1,
    ACTIONS(140), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [848] = 2,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(86), 1,
      sym_qualified_name,
  [855] = 1,
    ACTIONS(142), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [860] = 2,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(146), 1,
      anon_sym_COMMA,
  [867] = 1,
    ACTIONS(133), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [872] = 1,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [877] = 1,
    ACTIONS(150), 2,
      anon_sym_LBRACE,
      anon_sym_PLUS,
  [882] = 2,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    ACTIONS(154), 1,
      anon_sym_COMMA,
  [889] = 1,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [894] = 1,
    ACTIONS(158), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [899] = 1,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [904] = 1,
    ACTIONS(162), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [909] = 2,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    ACTIONS(164), 1,
      anon_sym_COMMA,
  [916] = 2,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
    ACTIONS(167), 1,
      anon_sym_COMMA,
  [923] = 1,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
  [927] = 1,
    ACTIONS(172), 1,
      anon_sym_COLON,
  [931] = 1,
    ACTIONS(174), 1,
      anon_sym_sig,
  [935] = 1,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
  [939] = 1,
    ACTIONS(178), 1,
      anon_sym_COLON,
  [943] = 1,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
  [947] = 1,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
  [951] = 1,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
  [955] = 1,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
  [959] = 1,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
  [963] = 1,
    ACTIONS(190), 1,
      aux_sym_constant_token1,
  [967] = 1,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
  [971] = 1,
    ACTIONS(194), 1,
      anon_sym_LBRACE,
  [975] = 1,
    ACTIONS(113), 1,
      anon_sym_sig,
  [979] = 1,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
  [983] = 1,
    ACTIONS(198), 1,
      anon_sym_COLON,
  [987] = 1,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
  [991] = 1,
    ACTIONS(95), 1,
      anon_sym_sig,
  [995] = 1,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
  [999] = 1,
    ACTIONS(204), 1,
      anon_sym_LBRACE,
  [1003] = 1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [1007] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
  [1011] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
  [1015] = 1,
    ACTIONS(212), 1,
      anon_sym_sig,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 52,
  [SMALL_STATE(5)] = 80,
  [SMALL_STATE(6)] = 106,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 162,
  [SMALL_STATE(9)] = 190,
  [SMALL_STATE(10)] = 218,
  [SMALL_STATE(11)] = 246,
  [SMALL_STATE(12)] = 274,
  [SMALL_STATE(13)] = 302,
  [SMALL_STATE(14)] = 321,
  [SMALL_STATE(15)] = 346,
  [SMALL_STATE(16)] = 365,
  [SMALL_STATE(17)] = 384,
  [SMALL_STATE(18)] = 394,
  [SMALL_STATE(19)] = 404,
  [SMALL_STATE(20)] = 414,
  [SMALL_STATE(21)] = 424,
  [SMALL_STATE(22)] = 434,
  [SMALL_STATE(23)] = 450,
  [SMALL_STATE(24)] = 460,
  [SMALL_STATE(25)] = 470,
  [SMALL_STATE(26)] = 480,
  [SMALL_STATE(27)] = 490,
  [SMALL_STATE(28)] = 506,
  [SMALL_STATE(29)] = 516,
  [SMALL_STATE(30)] = 526,
  [SMALL_STATE(31)] = 536,
  [SMALL_STATE(32)] = 546,
  [SMALL_STATE(33)] = 562,
  [SMALL_STATE(34)] = 572,
  [SMALL_STATE(35)] = 582,
  [SMALL_STATE(36)] = 592,
  [SMALL_STATE(37)] = 607,
  [SMALL_STATE(38)] = 617,
  [SMALL_STATE(39)] = 631,
  [SMALL_STATE(40)] = 645,
  [SMALL_STATE(41)] = 659,
  [SMALL_STATE(42)] = 671,
  [SMALL_STATE(43)] = 683,
  [SMALL_STATE(44)] = 697,
  [SMALL_STATE(45)] = 704,
  [SMALL_STATE(46)] = 711,
  [SMALL_STATE(47)] = 724,
  [SMALL_STATE(48)] = 734,
  [SMALL_STATE(49)] = 744,
  [SMALL_STATE(50)] = 754,
  [SMALL_STATE(51)] = 764,
  [SMALL_STATE(52)] = 774,
  [SMALL_STATE(53)] = 784,
  [SMALL_STATE(54)] = 794,
  [SMALL_STATE(55)] = 804,
  [SMALL_STATE(56)] = 814,
  [SMALL_STATE(57)] = 824,
  [SMALL_STATE(58)] = 831,
  [SMALL_STATE(59)] = 836,
  [SMALL_STATE(60)] = 843,
  [SMALL_STATE(61)] = 848,
  [SMALL_STATE(62)] = 855,
  [SMALL_STATE(63)] = 860,
  [SMALL_STATE(64)] = 867,
  [SMALL_STATE(65)] = 872,
  [SMALL_STATE(66)] = 877,
  [SMALL_STATE(67)] = 882,
  [SMALL_STATE(68)] = 889,
  [SMALL_STATE(69)] = 894,
  [SMALL_STATE(70)] = 899,
  [SMALL_STATE(71)] = 904,
  [SMALL_STATE(72)] = 909,
  [SMALL_STATE(73)] = 916,
  [SMALL_STATE(74)] = 923,
  [SMALL_STATE(75)] = 927,
  [SMALL_STATE(76)] = 931,
  [SMALL_STATE(77)] = 935,
  [SMALL_STATE(78)] = 939,
  [SMALL_STATE(79)] = 943,
  [SMALL_STATE(80)] = 947,
  [SMALL_STATE(81)] = 951,
  [SMALL_STATE(82)] = 955,
  [SMALL_STATE(83)] = 959,
  [SMALL_STATE(84)] = 963,
  [SMALL_STATE(85)] = 967,
  [SMALL_STATE(86)] = 971,
  [SMALL_STATE(87)] = 975,
  [SMALL_STATE(88)] = 979,
  [SMALL_STATE(89)] = 983,
  [SMALL_STATE(90)] = 987,
  [SMALL_STATE(91)] = 991,
  [SMALL_STATE(92)] = 995,
  [SMALL_STATE(93)] = 999,
  [SMALL_STATE(94)] = 1003,
  [SMALL_STATE(95)] = 1007,
  [SMALL_STATE(96)] = 1011,
  [SMALL_STATE(97)] = 1015,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(51),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(42),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(97),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 12),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 7),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 10),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 9),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 5, .production_id = 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 9, .production_id = 14),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 11),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 4, .production_id = 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 5, .production_id = 5),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 8),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 7, .production_id = 8),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 6, .production_id = 6),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 5, .production_id = 4),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 11),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_definition, 8, .production_id = 13),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name_list, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name_list, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_list, 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_in_list, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_in_list, 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sig_in_list_repeat1, 2),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sig_in_list_repeat1, 2), SHIFT_REPEAT(59),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 4),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 5),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_name, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 6),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__field_list, 4),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 2),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__field_list, 1), SHIFT(5),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__field_list, 3), SHIFT(69),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_list, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_extends, 2, .production_id = 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sig_in, 2, .production_id = 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplicity, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_Alloy6(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
